apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    app: dex
    role: overlord
  name: dex-overlord
spec:
  replicas: 1
  selector:
    app: dex
    role: overlord
  template:
    metadata:
      labels:
        app: dex
        role: overlord
    spec:
      containers:
          - image: quay.io/coreos/dex
            name: dex-overlord
            command: ["/opt/dex/bin/dex-overlord", "-key-secret", "XXXXXXXXXXXXX", "-db-url", "postgres://postgres@auth-postgres.default.tectonic.local:5432/auth?sslmode=disable"]
            ports:
            - containerPort: 5557
              name: overlord-port
