apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    app: dex
    role: worker
  name: dex-worker
spec:
  replicas: 1
  selector:
    app: dex
    role: worker
  template:
    metadata:
      labels:
        app: dex
        role: worker
    spec:
      containers:
          - image: quay.io/coreos/dex
            name: dex-worker
            command: ["/opt/dex/bin/dex-worker", "-issuer", "http://dex-worker.default.tectonic.local:5556", "-key-secret", "XXXXXXXXXXX", "-db-url", "postgres://postgres@auth-postgres.default.tectonic.local:5432/auth?sslmode=disable"]
            ports:
            - containerPort: 5556
              name: worker-port
            livenessProbe:
              httpGet:
                path: /health
                port: 5556
              initialDelaySeconds: 15
              timeoutSeconds: 1

