apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: dex
    role: overlord
  name: dex-overlord
spec:
  replicas: 1
  selector:
    app: dex
    role: overlord
  template:
    metadata:
      labels:
        app: dex
        role: overlord
    spec:
      containers:
          - image: quay.io/coreos/dex
            name: dex-overlord
            command: ["/opt/dex/bin/dex-overlord", "-key-secrets", "eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHg=", "-db-url", "postgres://postgres@dex-postgres.default:5432/postgres?sslmode=disable"]
            ports:
            - containerPort: 5557
              name: overlord-port
            livenessProbe:
              httpGet:
                path: /health
                port: 5557
              initialDelaySeconds: 15
              timeoutSeconds: 1
