sudo: required
services:
  - docker 

language: go

go:
 - 1.4.3
 - 1.5.3

env:
  - DEX_TEST_DSN="postgres://postgres@127.0.0.1:15432/postgres?sslmode=disable" ISOLATED=true

install:
 - go get golang.org/x/tools/cmd/cover
 - go get golang.org/x/tools/cmd/vet
 - docker pull quay.io/coreos/postgres

script:
 - docker run -d -p 127.0.0.1:15432:5432 quay.io/coreos/postgres
 - ./test
 - ./test-functional

after_success:
  - if [[ "$TRAVIS_GO_VERSION" == "1.5.3" && "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master"  ]]; then ./build-docker-push ;fi

notifications:
  email: false
