sudo: required
services:
  - docker 

language: go
go:
 - 1.4.3
 - 1.5.2

env:
  - DEX_TEST_DSN="postgres://postgres@127.0.0.1:15432/postgres?sslmode=disable" ISOLATED=true

install:
 - go get golang.org/x/tools/cmd/cover
 - go get golang.org/x/tools/cmd/vet
 - docker pull quay.io/coreos/postgres

script:
 - docker run -d -p 127.0.0.1:15432:5432 quay.io/coreos/postgres
 - ./test

notifications:
  email: false
